services:
  - type: web
    name: buffet-backend
    env: node
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
