// Provider abstraction: Yahoo Finance first, then exchange-aware fallbacks.
const yahoo = require('./yahooService');
const PROVIDER = process.env.DATA_PROVIDER || 'yahoo';
const AV_KEY = process.env.ALPHA_VANTAGE_API_KEY || null;
const HTTP_TIMEOUT_MS = 8000;
function safeNumber(v) { if (v == null || v === '') return null; const n = Number(v); return Number.isFinite(n) ? n : null; }
function httpGetJson(url) { const c=new AbortController(); const t=setTimeout(()=>c.abort(),HTTP_TIMEOUT_MS); return fetch(url,{signal:c.signal,headers:{'User-Agent':'stock-tracking-app/1.0'}}).then(async r=>{clearTimeout(t);if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}).catch(e=>{clearTimeout(t);throw e;}); }
function stooqCandidates(symbol) {
  const s=String(symbol||'').trim().toLowerCase(); if(!s||s.includes('^')) return [];
  const direct=s.includes('.') ? [s] : [`${s}.us`];
  if(s.endsWith('.de')) direct.push(`${s.slice(0,-3)}.de`);
  if(s.endsWith('.l')) direct.push(`${s.slice(0,-2)}.uk`);
  return [...new Set(direct)];
}
function formatDate(d){return d.toISOString().slice(0,10).replace(/-/g,'');}
async function fetchStooqHistory(symbol,days=365){const end=new Date(),start=new Date();start.setDate(end.getDate()-days);for(const ss of stooqCandidates(symbol)){try{const p=new URLSearchParams({s:ss,i:'d',d1:formatDate(start),d2:formatDate(end)});const c=new AbortController(),t=setTimeout(()=>c.abort(),HTTP_TIMEOUT_MS);let r;try{r=await fetch(`https://stooq.com/q/d/l/?${p}`,{signal:c.signal,headers:{'User-Agent':'stock-tracking-app/1.0'}})}finally{clearTimeout(t)}if(!r.ok)continue;const lines=(await r.text()).trim().split(/\r?\n/);if(lines.length<2)continue;const rows=lines.slice(1).map(x=>{const [date,open,high,low,close,volume]=x.split(',');return{date,open:safeNumber(open),high:safeNumber(high),low:safeNumber(low),close:safeNumber(close),volume:safeNumber(volume),adjClose:safeNumber(close)}}).filter(x=>x.date&&x.close!=null);if(rows.length)return rows}catch(e){console.error(`[stooq] ${symbol}:`,e.message)}}return[]}
function avEnabled(){return !!AV_KEY}
async function fetchAlphaVantageHistory(symbol,days=365){const json=await httpGetJson(`https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=${encodeURIComponent(symbol)}&outputsize=compact&apikey=${encodeURIComponent(AV_KEY)}`);const series=json?.['Time Series (Daily)'];if(!series)return[];const cutoff=new Date();cutoff.setDate(cutoff.getDate()-days);const cut=cutoff.toISOString().slice(0,10);return Object.entries(series).sort((a,b)=>a[0].localeCompare(b[0])).map(([date,d])=>({date,open:safeNumber(d['1. open']),high:safeNumber(d['2. high']),low:safeNumber(d['3. low']),close:safeNumber(d['4. close']),adjClose:safeNumber(d['5. adjusted close']),volume:safeNumber(d['6. volume'])})).filter(x=>x.close!=null&&x.date>=cut)}
async function fetchQuote(symbol){const primary=await yahoo.fetchQuote(symbol);if(primary?.price!=null)return primary;if(avEnabled())try{const q=await httpGetJson(`https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=${encodeURIComponent(symbol)}&apikey=${encodeURIComponent(AV_KEY)}`);const g=q?.['Global Quote'];if(g?.['05. price'])return{symbol,price:safeNumber(g['05. price']),change:safeNumber(g['09. change']),changePercent:safeNumber(String(g['10. change percent']||'').replace('%','')),previousClose:safeNumber(g['08. previous close']),open:safeNumber(g['02. open']),dayHigh:safeNumber(g['03. high']),dayLow:safeNumber(g['04. low']),volume:safeNumber(g['06. volume']),currency:null,timestamp:new Date().toISOString()}}catch(e){console.error(`[provider] AV quote ${symbol}:`,e.message)}
const h=await fetchStooqHistory(symbol,14);if(h.length){const last=h[h.length-1],prev=h[h.length-2];const ch=prev?.close!=null?last.close-prev.close:0;return{symbol,price:last.close,previousClose:prev?.close??last.close,change:ch,changePercent:prev?.close?ch/prev.close*100:0,currency:symbol.toUpperCase().endsWith('.DE')?'EUR':'USD',timestamp:last.date}}return null}
async function fetchFundamentals(symbol){return yahoo.fetchFundamentals(symbol)}
async function fetchNews(symbol){const data=await yahoo.fetchNews(symbol);const wanted=String(symbol||'').trim().toUpperCase().split('.')[0];const relevant=a=>{const t=Array.isArray(a?.relatedTickers)?a.relatedTickers:[];return !t.length||t.some(x=>String(x||'').trim().toUpperCase().split('.')[0]===wanted)};return{all:data.all.filter(relevant),company:data.company.filter(relevant),geopolitics:data.geopolitics.filter(relevant)}}
async function fetchCalendar(symbol){return yahoo.fetchCalendar(symbol)}
async function fetchHistory(symbol,range='6mo',interval='1d',days){const primary=await yahoo.fetchHistory(symbol,range,interval);if(primary?.length)return primary;const fallbackDays=days||({ '1mo':30,'3mo':90,'6mo':180,'1y':365,'2y':730,'5y':1825}[range]||365);if(avEnabled())try{const r=await fetchAlphaVantageHistory(symbol,fallbackDays);if(r.length)return r}catch(e){console.error(`[provider] AV history ${symbol}:`,e.message)}return fetchStooqHistory(symbol,fallbackDays)}
async function searchSymbol(query){return yahoo.searchSymbol(query)}
function clearCache(){yahoo.clearCache()}
module.exports={name:PROVIDER,fallbacks:{alphaVantage:avEnabled(),stooq:true},fetchQuote,fetchFundamentals,fetchNews,fetchCalendar,fetchHistory,searchSymbol,clearCache,_internals:{stooqCandidates,safeNumber}};