module.exports = (sequelize, DataTypes) => {
  const Fundamental = sequelize.define('Fundamental', {
    snapshotAt: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
    peRatio: DataTypes.FLOAT,
    forwardPe: DataTypes.FLOAT,
    pegRatio: DataTypes.FLOAT,
    pbRatio: DataTypes.FLOAT,
    psRatio: DataTypes.FLOAT,
    eps: DataTypes.FLOAT,
    forwardEps: DataTypes.FLOAT,
    dividendRate: DataTypes.FLOAT,
    dividendYield: DataTypes.FLOAT,
    payoutRatio: DataTypes.FLOAT,
    marketCap: DataTypes.BIGINT,
    beta: DataTypes.FLOAT,
    fiftyTwoWeekHigh: DataTypes.FLOAT,
    fiftyTwoWeekLow: DataTypes.FLOAT,
    fiftyDayAverage: DataTypes.FLOAT,
    twoHundredDayAverage: DataTypes.FLOAT,
    revenue: DataTypes.BIGINT,
    earningsGrowth: DataTypes.FLOAT,
    revenueGrowth: DataTypes.FLOAT,
    profitMargins: DataTypes.FLOAT,
    operatingMargins: DataTypes.FLOAT,
    grossMargins: DataTypes.FLOAT,
    freeCashflow: DataTypes.BIGINT,
    operatingCashflow: DataTypes.BIGINT,
    totalCash: DataTypes.BIGINT,
    totalDebt: DataTypes.BIGINT,
    debtToEquity: DataTypes.FLOAT,
    currentRatio: DataTypes.FLOAT,
    quickRatio: DataTypes.FLOAT,
    roa: DataTypes.FLOAT,
    roc: DataTypes.FLOAT,
    targetMeanPrice: DataTypes.FLOAT,
    targetHighPrice: DataTypes.FLOAT,
    targetLowPrice: DataTypes.FLOAT,
    recommendationMean: DataTypes.FLOAT,
    recommendationKey: DataTypes.STRING,
    numberOfAnalystOpinions: DataTypes.INTEGER,
    sharesOutstanding: DataTypes.BIGINT,
    floatShares: DataTypes.BIGINT,
    heldPercentInsiders: DataTypes.FLOAT,
    heldPercentInstitutions: DataTypes.FLOAT,
    shortRatio: DataTypes.FLOAT,
    shortPercentOfFloat: DataTypes.FLOAT,
    price: DataTypes.FLOAT,
    change: DataTypes.FLOAT,
    changePercent: DataTypes.FLOAT,
    dayHigh: DataTypes.FLOAT,
    dayLow: DataTypes.FLOAT,
    yearHigh: DataTypes.FLOAT,
    yearLow: DataTypes.FLOAT,
    volume: DataTypes.BIGINT,
    avgVolume: DataTypes.BIGINT,
    previousClose: DataTypes.FLOAT,
  }, { timestamps: true });

  Fundamental.associate = (models) => {
    Fundamental.belongsTo(models.Stock, { foreignKey: 'stockId', as: 'stock' });
  };

  return Fundamental;
};
